# Generated by Django 2.2.3 on 2019-07-07 06:21

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('url', models.URLField(verbose_name='url')),
            ],
            options={
                'verbose_name': 'socket',
                'verbose_name_plural': 'sockets',
            },
        ),
        migrations.AddIndex(
            model_name='websocket',
            index=models.Index(fields=['created'], name='blockchain__created_57d82c_idx'),
        ),
    ]
