# Generated by Django 2.2.3 on 2019-07-08 02:20

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True, verbose_name='index')),
                ('previous_block_hash', models.CharField(max_length=128, unique=True, verbose_name='previous block hash')),
                ('hash', models.CharField(max_length=128, unique=True, verbose_name='block hash')),
                ('difficulty', models.IntegerField(verbose_name='difficulty')),
                ('nonce', models.IntegerField(verbose_name='nonce')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('data', models.TextField(verbose_name='transaction data')),
            ],
            options={
                'verbose_name': 'block',
                'verbose_name_plural': 'blocks',
            },
        ),
        migrations.CreateModel(
            name='WebSocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uri', models.URLField(unique=True, verbose_name='URI')),
            ],
            options={
                'verbose_name': 'socket',
                'verbose_name_plural': 'sockets',
            },
        ),
        migrations.AddIndex(
            model_name='websocket',
            index=models.Index(fields=['created'], name='blockchain__created_57d82c_idx'),
        ),
    ]
