# Generated by Django 2.2.3 on 2019-07-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True, verbose_name='index')),
                ('previous_block_hash', models.CharField(max_length=128, unique=True, verbose_name='previous block hash')),
                ('hash', models.CharField(max_length=128, unique=True, verbose_name='block hash')),
                ('difficulty', models.IntegerField(verbose_name='difficulty')),
                ('nonce', models.IntegerField(verbose_name='nonce')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('data', models.TextField(verbose_name='transaction data')),
            ],
            options={
                'verbose_name': 'block',
                'verbose_name_plural': 'blocks',
            },
        ),
        migrations.AlterField(
            model_name='websocket',
            name='url',
            field=models.URLField(unique=True, verbose_name='url'),
        ),
    ]
