# Generated by Django 2.2.3 on 2019-07-07 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20190707_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websocket',
            name='url',
        ),
        migrations.AddField(
            model_name='websocket',
            name='uri',
            field=models.URLField(default=django.utils.timezone.now, unique=True, verbose_name='URI'),
            preserve_default=False,
        ),
    ]
