import logging

from .block import Block

GENESIS_BLOCK_DATA = 'This is a genesis block.'
GENESIS_BLOCK_TIMESTAMP = 1562132041


class Blockchain:
    logger = logging.getLogger(__name__)

    def __init__(self):
        self.chain = [self.genesis_block, ]

    def new_block(self, data):
        block = Block(self.last_block.index + 1, self.last_block.hash, data)
        self.chain.append(block)

    @property
    def genesis_block(self):
        return Block(index=0, previous_block_hash=None, data=GENESIS_BLOCK_DATA, timestamp=GENESIS_BLOCK_TIMESTAMP)

    @property
    def last_block(self):
        return self.chain[-1]

    def validate_new_block(self, new_block):
        if self.last_block.index + 1 != new_block.index:
            self.logger.error('invalid block: new block index is not consecutive.')
            return False
        elif self.last_block.hash != new_block.previous_block_hash:
            self.logger.error('invalid block: last block hash does not match previous block hash in new block.')
            return False
        elif self.last_block.hash != self.last_block.create_hash():
            self.logger.error('invalid block: last block hash does not match hash generated by last block.')
            return False
        elif new_block.hash != new_block.create_hash():
            self.logger.error('invalid block: new block hash does not match hash generated by new block.')
            return False

        return True
